# Required for dataset registration hooks
import pycheribenchplot.analysis
import pycheribenchplot.core.pidmap
import pycheribenchplot.core.procstat
import pycheribenchplot.drcachesim.analysis
import pycheribenchplot.drcachesim.plot
import pycheribenchplot.generic.task
import pycheribenchplot.kernel_static.dataset
import pycheribenchplot.kernel_static.plot
import pycheribenchplot.netperf.analysis
import pycheribenchplot.netperf.dataset
import pycheribenchplot.netperf.plot
import pycheribenchplot.netstat.dataset
import pycheribenchplot.pmc.analysis
import pycheribenchplot.pmc.dataset
import pycheribenchplot.pmc.plot
import pycheribenchplot.qemu.cheribsd_counters
import pycheribenchplot.qemu.cheribsd_counters_plot
import pycheribenchplot.qemu.dataset
import pycheribenchplot.qemu.plot
import pycheribenchplot.spec.dataset
import pycheribenchplot.vmstat.dataset
import pycheribenchplot.vmstat.plot
