#!/bin/python

import argparse as ap
import json
import shutil
import subprocess
import re
from collections import defaultdict
from pathlib import Path

import matplotlib.pyplot as plt
import polars as pl
import seaborn as sns

def main():
    parser = ap.ArgumentParser("QEMU instruction trace icount diff tool")
    parser.add_argument("data_file", nargs="+", type=Path,
                        help="Path to csv files generated by qemu-trace-counter.py")
    parser.add_argument("--output", type=Path, default=Path.cwd() / "icount-diff.pdf",
                        help="Output plot file")

    args = parser.parse_args()

    data = []
    for path in args.data_file:
        df = pl.read_csv(path)
        df = df.with_columns(pl.lit(path.stem).alias("name"))
        data.append(df)

    baseline = args.data_file[0].stem

    all_df = pl.concat(data, how="vertical")
    base_df = all_df.filter(pl.col("name") == baseline).select(
        pl.col("fn"), pl.col("icount").alias("icount_baseline"))
    join_df = all_df.join(base_df, on="fn")

    diff_df = (
        join_df
        .with_columns((pl.col("icount") - pl.col("icount_baseline")).alias("icount_diff"))
        .filter(pl.col("name") != baseline)
    )

    fig, ax = plt.subplots()
    sns.set_theme()
    plt.grid(axis="x", which="major", linestyle="--", linewidth=0.5)

    sns.barplot(x="icount_diff", y="fn", data=diff_df, hue="name")

    fig.tight_layout()
    fig.savefig(args.output)

if __name__ == "__main__":
    main()
